Progression Item Locations:
  dungeons:
    # This controls whether dungeon locations are randomized.
    'false': 0
    'true': 50

  tingle_chests:
    # Tingle Chests are hidden in dungeons and must be bombed to make them appear. (2 in DRC, 1 each in FW, TotG, ET, and WT). This controls whether they are randomized.
    'false': 50
    'true': 0

  puzzle_secret_caves:
    # This controls whether the rewards from puzzle-focused secret caves are randomized locations.
    'false': 0
    'true': 50

  combat_secret_caves:
    # This controls whether the rewards from combat-focused secret caves (besides Savage Labyrinth) are randomized locations.
    'false': 50
    'true': 0

  savage_labyrinth:
    # This controls whether the two locations in Savage Labyrinth are randomized.
    'false': 50
    'true': 0

  island_puzzles:
    # This controls whether various island puzzles are randomized (e.g., chests hidden in unusual places).
    'false': 50
    'true': 0

  great_fairies:
    # This controls whether the items given by Great Fairies are randomized.
    'false': 0
    'true': 50

  submarines:
    # This controls whether submarines are randomized.
    'false': 50
    'true': 0

  lookout_platforms_and_rafts:
    # This controls whether lookout platforms and rafts are randomized.
    'false': 50
    'true': 0

  short_sidequests:
    # This controls whether sidequests that can be completed quickly are randomized.
    'false': 50
    'true': 0

  long_sidequests:
    # This controls whether long sidequests (e.g., Lenzo's assistant, withered trees, goron trading) are randomized.
    'false': 50
    'true': 0

  spoils_trading:
    # This controls whether the items you get by trading in spoils to NPCs are randomized.
    'false': 50
    'true': 0

  eye_reef_chests:
    # This controls whether the chests that appear after clearing out the eye reefs are randomized.
    'false': 50
    'true': 0

  big_octos_and_gunboats:
    # This controls whether the items dropped by Big Octos and Gunboats are randomized.
    'false': 50
    'true': 0

  miscellaneous:
    # Miscellaneous locations that don't fit into any of the above categories (outdoors chests, wind shrine, Cyclos, etc).
    # This controls whether these are randomized.
    'false': 50
    'true': 0

  minigames:
    # This controls whether most minigames are randomized (auctions, mail sorting, barrel shooting, bird-man contest).
    'false': 50
    'true': 0

  battlesquid:
    # This controls whether the Windfall battleship minigame is randomized.
    'false': 50
    'true': 0

  free_gifts:
    # This controls whether gifts freely given by NPCs are randomized (Tott, Salvage Corp, imprisoned Tingle).
    'false': 0
    'true': 50

  mail:
    # This controls whether items received from the mail are randomized.
    'false': 50
    'true': 0

  expensive_purchases:
    # This controls whether items that cost many Rupees are randomized (Rock Spire shop, auctions, Tingle's letter,
    # trading quest).
    'false': 0
    'true': 50

  "Sunken Treasure (From Triforce Charts)":
    # This controls whether the sunken treasure chests marked on Triforce Charts are randomized.
    'false': 50
    'true': 0

  "Sunken Treasure (From Treasure Charts)":
    # This controls whether the sunken treasure chests marked on Treasure Charts are randomized.
    'false': 50
    'true': 0

Additional Randomization Options:
  sword_mode:
    # Controls whether you start with the Hero's Sword, the Hero's Sword is randomized, or if there are no swords in the
    # entire game.
    # 
    # - **AP Preferences** The tracker will check the sword item based off of the settings set in AP.
    # - **Swordless:** You will start the game with no sword, and won't be able to find it anywhere. You have to beat the
    #   entire game using other items as weapons instead of the sword. (Note that Phantom Ganon in FF becomes vulnerable
    #   to Skull Hammer in this mode.)
    ap_preferences: 50
    swordless: 0

  key_lunacy:
    # Not sure what this does, but If i remember correctly, this setting does not keep keys inside their own dungeons
    false: 50
    true: 0

  race_mode:
    # Tells the tracker whatever or not the rando is being done in race mode.
    'false': 50
    'true': 0

  randomize_entrances:
    # When any settings of this type are configured in AP, The tracker will know that and configure this setting for you. This allows you to track entrances that are randomized.
    false: 50
    true: 0

  randomize_charts:
    # Randomizes which sector is drawn on each Triforce/Treasure Chart.
    'false': 50
    'true': 0

Convenience Tweaks:

  skip_boss_rematches:
    # Removes the door in Ganon's Tower that only unlocks when you defeat the rematch versions of Gohma, Kalle Demos,
    # Jalhalla, and Molgera.
    'false': 0
    'true': 50
