name: CI
permissions:
  contents: write
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20.x'

      - name: Install npm packages
        run: |
          set -e
          npm install

      - name: Build UI
        run: |
          set -e
          npm run build:production

      - name: Run tests
        run: |
          set -e
          npm test

      - name: Run eslint
        run: |
          set -e
          npm run lint

      - name: Generate docs
        run: |
          set -e
          npm run docs
          mv ./docs ./dist/

          
        
      - name: Deploy branches
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone -b gh-pages-main -q "https://github.com/josephanimate2021/twwr-ap-tracker" ./repo
          rm -rf ./repo/${{ github.ref_name }}
          git clone -b gh-pages-${{ github.ref_name }} -q "https://github.com/josephanimate2021/twwr-ap-tracker" ./repo/${{ github.ref_name }}
          rm -r ./repo/${{ github.ref_name }}/.git
          git clone -b old -q "https://github.com/josephanimate2021/twwr-ap-tracker" ./repo/${{ github.ref_name }}/old
          cd repo
          git checkout --orphan gh-pages-temp
          git add ${{ github.ref_name }}/
          git add .
          git commit -m "Deploy main branch and ${{ github.ref_name }} branch together"
          git push --force https://action:${{ secrets.GITHUB_TOKEN }}@github.com/josephanimate2021/twwr-ap-tracker.git gh-pages-temp:gh-pages-main
          git push https://action:${{ secrets.GITHUB_TOKEN }}@github.com/josephanimate2021/twwr-ap-tracker.git :gh-pages-${{ github.ref_name }}
      - name: Deploy
        if: github.repository == 'josephanimate2021/twwr-ap-tracker' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages-main
          publish_dir: ./dist
