name: Deploy Branch (For Static Files)
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Pages Repo
        run: |
          git checkout gh-pages-main
          
      - name: Clone the ${{ github.ref_name }} branch
        run: |
          git clone -b ${{ github.ref_name }} https://github.com/josephanimate2021/twwr-ap-tracker ./${{ github.ref_name }}
          rm -rf ./${{ github.ref_name }}/.git
          
      - name: Deploy The ${{ github.ref_name }} branch to the Github Pages branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Deployed the main and ${{ github.ref_name }} branches together"
          git push https://action:${{ secrets.GITHUB_TOKEN }}@github.com/josephanimate2021/twwr-ap-tracker.git
