name: Deploy Branch (For Static Files)
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-main
      - name: Deploy The ${{ github.ref_name }} branch to the Github Pages branch
        run: |
          ls
