name: Deploy Branch
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  build_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ github.ref_name }}

  combined_deploy:
    runs-on: ubuntu-latest
    needs: build_branch
    concurrency: combined_deploy

    steps:
      - name: Deploy branches
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone -b gh-pages-${{ github.ref_name }} -q "https://github.com/josephanimate2021/twwr-ap-tracker" ./${{ github.ref_name }}
          rm -r ./${{ github.ref_name }}/.git
          git add .
          git commit -m "Deployed the main and ${{ github.ref_name }} branches together"
          git push https://action:${{ secrets.GITHUB_TOKEN }}@github.com/josephanimate2021/twwr-ap-tracker.git
