name: Manual Pages Deployment
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20.x'

      - name: Install npm packages
        run: |
          set -e
          npm install

      - name: Build UI
        run: |
          set -e
          npm run build:production

      - name: Run tests
        run: |
          set -e
          npm test

      - name: Run eslint
        run: |
          set -e
          npm run lint

      - name: Generate docs
        run: |
          set -e
          npm run docs
          mv ./docs ./dist/

          
        
      - name: Add the old branch to pages deployment.
        run: |
          git clone -b old "https://github.com/josephanimate2021/twwr-ap-tracker" ./dist/old
          rm -r ./dist/old/.git
          
      - name: Deploy
        if: github.repository == 'josephanimate2021/twwr-ap-tracker' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages-main
          publish_dir: ./dist
